config/routes.rb
Rails.application.routes.draw do
  mount Spina::Engine => '/'
  resources :contents

end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  @allpages = Spina::Page.all
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params[:content]
    end
end

app/controllers/spina/pages_controller.rb
module Spina
  class PagesController < ApplicationController
    before_action :current_user_can_view_page?, except: [:robots]

    def homepage
      @pages = Spina::Page.all
      render_with_template(page)
    end

    def show
      if should_skip_to_first_child?
        if page.is_root?
          redirect_to spina.subpage_path(page, first_live_child) and return
        else
          redirect_to spina.third_level_page_path(page.parent, page, first_live_child) and return
        end
      elsif page.link_url.present?
        redirect_to page.link_url and return
      end

      render_with_template(page)
    end

    private

    def page
      @page ||= (action_name == 'homepage') ? Page.find_by(name: 'homepage') : Page.find(params[:id])
    end
    helper_method :page

    def current_user_can_view_page?
      raise ActiveRecord::RecordNotFound unless page.live? || current_user.present?
    end

    def should_skip_to_first_child?
      page.skip_to_first_child && first_live_child
    end

    def first_live_child
      page.children.sorted.live.first
    end

    def render_with_template(page)
      render layout: "#{current_theme.to_s.underscore}/application", template: "#{current_theme.to_s.underscore}/pages/#{page.view_template || 'show'}"
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>
<div class="parallax-container">


<h1>Mom's Club of Layton</h1>


<div class="parallax"><img src="images/parallax1.jpg"></div>
<div class="parallax"><img src="images/parallax1.jpg"></div>
<div class="parallax"><img src="images/parallax1.jpg"></div>
<div class="parallax"><img src="images/parallax1.jpg"></div>
<div class="parallax"><img src="images/parallax1.jpg"></div>
<div class="parallax"><img src="images/parallax1.jpg"></div>
<div class="parallax"><img src="images/parallax1.jpg"></div>




<div class="parallax"><img src="images/parallax1.jpg"></div>
</div>

















<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/default/pages/homepage.html.erb
<% [1,2,3,4,5] %>
<% @pages.each do |page| %>
  <div class="parallax-container">
    <div class="parallax grey lighten-5">
      <div class="row">
        <div class="col s10 offset-s1">
          <h1><%= page.title %></h1>
          <%= page.content(:content).try(:html_safe) %>
        </div>
      </div>
    </div>
  </div>
  <div class="parallax-container" style="box-shadow:-10px 0 47px #000 inset;">
    <div class="parallax">
      <%= image_tag("#{page.id}.jpg", style: 'width:100%') %>
    </div>
  </div>
<% end %>

app/views/default/pages/show.html.erb
<h1><%= @page.title %></h1>

<%= @page.content(:content).try(:html_safe) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Momsclub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/default/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= current_account.name %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'spina/shared/navigation' %>
<div class="container-responsive">
  <%= yield %>
</div>
<footer class="page-footer purple lighten-4" style="margin-top:0px">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>
<script>
  $(document).ready(function(){
    $('.parallax').parallax();
  });
</script>
</body>
</html>

app/views/spina/shared/_navigation.html.erb
<% pages = current_user.present? ? Spina::Page.active : Spina::Page.live %>
<% menu = Spina::Pages::MenuPresenter.new(pages.in_menu.arrange(order: :position), self, @page) %>
<nav class="purple lighten-4">
  <a href="#" class="brand-logo black-text darken-4">MOM's Club of Layton</a>

  <%= menu.to_html %>
</nav>